### ISSUE TITLE
[VSFeat] Folder structure project for DevOps

### ISSUE THREAD

**Issue by ccastrotrejo** [Azure/LogicAppsUX#2131]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/LogicAppsUX/issues/2132
- [ ] https://github.com/Azure/LogicAppsUX/issues/2133
- [ ] https://github.com/Azure/LogicAppsUX/issues/2134
```

**Comment by ccastrotrejo** [comment]
Closing this since its been tracked in ADO
